version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smarthome-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smart_home_bda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: f@123!09f
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smarthome-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smarthome-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smarthome.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge