version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smarthome-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-smart_home_bda}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SmartHome2024!SecurePass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smarthome-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smarthome-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@smarthome.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-SmartHome2024!AdminPass}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge